9 adds GET /api/reviews/:review_id/comments functionality
Asileka/katsncgamesproject pull request #9
Opened 2022-07-07 12:38 UTC by Asileka

2022-07-07 14:07 UTC, HeatherEver reviewed
Nice work Kat - just think about the 200 test for a review with no comments, there made need to be some changes in your model or SQL query

2022-07-07 14:07 UTC, HeatherEver commented on __tests__/ncgamesapp.test.js
> +});
please can you add some error handling to this endpoint - 
- invalid review_id
- review not found
also what if the review has no comments - we would still like to return a 200 just with no comments to display

2022-07-07 15:51 UTC, Angaca commented on __tests__/ncgamesapp.test.js
> +        expect(msg).toBe("no comments found");
When we have a valid review with no comments on it we want to receive a 200 and an empty array. Imagine this being on a website would you expect an error if no one hasn't commented yet?

2022-07-07 15:51 UTC, Angaca requested changes
Please have a look at the comment I left :)

2022-07-08 09:16 UTC, Angaca commented on models/ncgamesmodel.js
> +        console.log(results.rows + " results.rows in checkId models");
remove logs

2022-07-08 09:17 UTC, Angaca commented on models/ncgamesmodel.js
> +        if (!results.rows.length) {
you can use the property rowCount instead of checking the rows.length

2022-07-08 09:17 UTC, Angaca approved these changes
Have a look at the comments for some very small changes but this is ready for merge!

2022-07-08 09:33 UTC, merged